"""tests/host/test_resampler_tables.py -- GitHub Issue #124: every resampler coefficient table the runtime adopts has
every phase summing to EXACTLY one in its fixed point, whatever its tap count or its window.

WHY. The chain's input always carries a mid-scale level: a decoded sample sits near its rest, and the native decode's
mono sum near 256 steps. A polyphase table whose phases do not all sum to the same value turns that level into a
pattern at the phase cycle's rate -- 32 000 / 125 = 256 Hz and its multiples -- inside the band. #124 measured it:
0.557 steps RMS at 16 taps, Kaiser beta 2.0, over the source's quantisation floor from the DC alone
(tools/v124taps.py, whole-sum against per-phase kernels). The exact per-phase sum is WHY a constant passes cleanly,
and until now it was checked for one table, the one in the tree (tests/host/test_audio_runtime.py, through
tools/gen_aresamp.py). A later table -- the native decoder's, another tap count, another beta -- that rounds its
phases independently would bring the artefact back into the runtime and nothing would say so.

WHAT IS HELD. Every two-dimensional constant integer table anywhere under src/ (any .c or .h, found by its
declaration, not by its file name) is either a resampler table -- GENERATED, its fixed point declared in its file's
comment ("Q15"), every one of its L rows summing to exactly 1 << Q, its shape the one its #defines state -- or named in
NOT_RESAMPLER here with the reason. Every table a file declares is checked, not only the first. And the generator's own
table, at its own parameters.
"""
import os
import re
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import gen_aresamp  # noqa: E402


DECL = re.compile(r"static\s+const\s+u?int(?:8|16|32|64)_t\s+(\w+)\s*\[([^\]]*)\]\s*\[([^\]]*)\]")
BODY = re.compile(r"static\s+const\s+u?int(?:8|16|32|64)_t\s+(\w+)\s*\[(\d+)\]\s*\[(\d+)\]\s*=\s*\{(.*?)\n\};", re.S)
# two-dimensional integer tables under src/ that are NOT resampler tables, each with its reason (none today)
NOT_RESAMPLER = {}


def sources():
    out = []
    for d, _dirs, files in os.walk(os.path.join(ROOT, "src")):
        out += [os.path.join(d, f) for f in files if f.endswith((".c", ".h"))]
    return sorted(out)


def declared():
    """{(path, name)} of every 2-D constant integer table declared under src/."""
    found = set()
    for path in sources():
        with open(path, encoding="utf-8") as f:
            for m in DECL.finditer(f.read()):
                found.add((path, m.group(1)))
    return found


def tables():
    return sorted(set(p for p, name in declared() if name not in NOT_RESAMPLER))


def parse_all(path):
    """(src, Q, [(name, L, T, rows)]) for every table the file declares with a body."""
    with open(path, encoding="utf-8") as f:
        src = f.read()
    q = re.search(r"\bQ(\d+)\b", src)
    out = []
    for m in BODY.finditer(src):
        rows = [[int(v) for v in r.split(",")] for r in re.findall(r"\{([^{}]*)\}", m.group(4))]
        out.append((m.group(1), int(m.group(2)), int(m.group(3)), rows))
    return src, (int(q.group(1)) if q else None), out


def parse(path):
    src, q, ts = parse_all(path)
    if q is None or not ts:
        return src, q, None, None
    name, L, T, rows = ts[0]
    return src, q, (name, L, T), rows


def phases_sum_exactly_one(rows, q):
    return all(sum(r) == (1 << q) for r in rows)


class EveryAdoptedTable(unittest.TestCase):
    def test_there_is_at_least_the_one_in_the_tree(self):
        self.assertIn(os.path.join(ROOT, "src", "audio", "gbp_aresamp_coef.h"), tables())
        self.assertEqual(declared(), {(os.path.join(ROOT, "src", "audio", "gbp_aresamp_coef.h"), "GBP_ARESAMP_COEF")})

    def test_every_table_of_every_file_has_every_phase_summing_to_exactly_one(self):
        for path in tables():
            src, q, ts = parse_all(path)
            name = os.path.relpath(path, ROOT)
            decl = [n for p, n in declared() if p == path and n not in NOT_RESAMPLER]
            self.assertEqual(sorted(t[0] for t in ts), sorted(decl), "%s: a declared table was not parsed" % name)
            self.assertIn("GENERATED by", src, name)
            self.assertIsNotNone(q, "%s: no fixed point stated in its header" % name)
            for tname, L, T, rows in ts:
                self.assertEqual(len(rows), L, (name, tname))
                self.assertTrue(all(len(r) == T for r in rows), (name, tname))
                bad = [i for i, r in enumerate(rows) if sum(r) != (1 << q)]
                self.assertEqual(bad, [], "%s %s: phases %s do not sum to %d" % (name, tname, bad[:8], 1 << q))

    def test_the_discovery_sees_a_table_whatever_its_file_is_called(self):
        src = "static const int32_t X_FIR[3][2] = {\n    {1, 2},\n};\nstatic const int16_t Y[2][2] = {\n};\n"
        self.assertEqual([m.group(1) for m in DECL.finditer(src)], ["X_FIR", "Y"])

    def test_the_defines_state_the_shape(self):
        for path in tables():
            src, _q, shape, _rows = parse(path)
            _n, L, T = shape
            self.assertRegex(src, r"#define \w+_L %du" % L)
            self.assertRegex(src, r"#define \w+_TAPS %du" % T)


class TheGeneratorKeepsIt(unittest.TestCase):
    def test_gen_aresamp_folds_every_phases_rounding(self):
        self.assertTrue(phases_sum_exactly_one(gen_aresamp.table(), gen_aresamp.Q))

    def test_the_check_is_not_vacuous(self):
        rows = [list(r) for r in gen_aresamp.table()]
        rows[37][3] += 1                                   # one unit off in one phase
        self.assertFalse(phases_sum_exactly_one(rows, gen_aresamp.Q))


if __name__ == "__main__":
    unittest.main()
