"""
GBP-VIDEO-001 fixture round trip on SYNTHETIC data, and the physical GBP-AV-SERVICE-001 fixture
replayed as the first cycle of the repeated service.

The synthetic path: the host mock run (tests/unit/test_gbp_video.c --dump-log — six admitted
cycles, both sources each, a frame flag every three VIDEO blocks, the delivery cap) is written in
the SD-log format together with its sequence sidecar; tools/probelog.py turns the log into a
replay script (marked SYNTHETIC; its "B" lines carry each block's CRC-32, never the bytes), and
the probe logic run on that script with the sidecar attached reaches the same result as the mock
run — every time-base read, PI read, interrupt-path operation, whole-block read and handler record
answered by the fixture and the sidecar, nothing invented. The generated files stay under build/
and are never placed under captures/fixtures/.

The physical path: the GBP-AV-SERVICE-001 fixture of 2026-09-16 (build avsvc-0001, commit d3a6d23)
is the EXACT PREFIX of cycle 0 of this state machine — that physical run is one cycle of this
loop. With max_deliveries = 1 it replays end to end: every one of its operations is consumed in
order, the second cycle is refused at the admission point, and the cause the device left latched
is acknowledged by the teardown. NO physical GBP-VIDEO-001 fixture exists; none is invented here.
"""
import os
import re
import subprocess
import sys
import tempfile
import unittest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import avseq  # noqa: E402
import probelog  # noqa: E402

BIN = os.path.join(ROOT, "build", "tests", "unit", "test_gbp_video")
OUTDIR = os.path.join(ROOT, "build", "tests", "unit")
NOTE = "SYNTHETIC: generated from the host mock (tests/unit/test_gbp_video.c --dump-log); NOT physical data"
PHYSICAL_AVSVC = os.path.join(ROOT, "captures", "fixtures", "hw-gamecube-gbp-2026-09-16-avsvc-0001.gbpreplay")
PHYSICAL_AVSVC_BLOCKS = os.path.join(ROOT, "captures", "fixtures", "hw-gamecube-gbp-2026-09-16-avsvc-0001-blocks.bin")
REPLAY_RE = re.compile(r"REPLAY step=(\d+) exhausted=(\d+) mismatches=(\d+) tick_polls=(\d+) timeline=(\d+) "
                       r"log_lines=(\d+) bulk_reads=(\d+) blocks_missing=(\d+) block_crc_mismatches=(\d+) record_resets=(\d+)")


def outdir():
    return OUTDIR if os.path.isdir(OUTDIR) else tempfile.mkdtemp()


def summary_fields(text):
    line = next(l for l in text.splitlines() if l.startswith("SUMMARY "))
    out = {}
    for tok in line[len("SUMMARY DONE "):].split(" "):
        if "=" in tok:
            k, v = tok.split("=", 1)
            out[k] = v
    return out


@unittest.skipUnless(os.path.isfile(BIN), "run `make -C tests/unit` to build the unit tests")
class SyntheticRoundTrip(unittest.TestCase):
    """log -> fixture -> replay: the regenerated run equals the original, operation by operation."""

    @classmethod
    def setUpClass(cls):
        d = outdir()
        cls.log = os.path.join(d, "video-replay-host.log")
        cls.seq = os.path.join(d, "video-replay-host-seq.bin")
        cls.fixture = os.path.join(d, "video-replay-host.gbpreplay")
        r = subprocess.run([BIN, "--dump-log", cls.log, cls.seq], check=True, capture_output=True, text=True)
        cls.original = summary_fields(r.stdout)
        header, records = probelog.parse_file(cls.log)
        cls.records = records
        with open(cls.fixture, "w", encoding="utf-8") as f:
            f.write(probelog.fixture(records, note=NOTE))
        r = subprocess.run([BIN, "--replay", cls.fixture, cls.seq], capture_output=True, text=True)
        cls.replay_rc = r.returncode
        cls.replayed = summary_fields(r.stdout)
        cls.stats = REPLAY_RE.search(r.stdout)

    def test_the_log_carries_the_new_records(self):
        kinds = {r["kind"] for r in self.records}
        for k in ("CYCU", "CYCW", "CYCH", "CYCD", "CYCR", "VBLK", "ABLK", "BOUNDARIES", "ADMISSION", "MATRIX", "ADMIT"):
            self.assertIn(k, kinds, k)
        # the compact records exist for every cycle, and the lean ones carry their raw pending read
        cycu = [r for r in self.records if r["kind"] == "CYCU"]
        self.assertEqual(len(cycu), int(self.original["deliveries"]))
        lean = [r for r in cycu if r["fields"]["verify"] == "0"]
        raws = [r for r in self.records if r["kind"] == "RAW" and str(r.get("tag", "")).startswith("READ-")]
        self.assertEqual(len(raws), len(lean))

    def test_the_fixture_is_marked_synthetic(self):
        with open(self.fixture, encoding="utf-8") as f:
            text = f.read()
        self.assertIn("# " + NOTE, text)
        self.assertTrue(text.startswith("# generated by tools/probelog.py"))

    def test_replay_consumes_every_operation(self):
        self.assertIsNotNone(self.stats)
        step, exhausted, mismatches = int(self.stats.group(1)), int(self.stats.group(2)), int(self.stats.group(3))
        self.assertGreater(step, 200)
        self.assertEqual(exhausted, 0)
        self.assertEqual(mismatches, 0)
        self.assertEqual(int(self.stats.group(5)), 1)                    # the physical time base drives ticks()
        self.assertEqual(int(self.stats.group(8)), 0)                    # blocks_missing
        self.assertEqual(int(self.stats.group(9)), 0)                    # block_crc_mismatches
        self.assertEqual(self.replay_rc, 0)

    def test_the_blocks_come_from_the_sidecar(self):
        self.assertEqual(int(self.stats.group(7)), 2 * int(self.original["deliveries"]))   # bulk_reads: AUDIO + VIDEO per cycle

    def test_the_record_is_reset_once_per_cycle_after_the_first(self):
        self.assertEqual(int(self.stats.group(10)), int(self.original["deliveries"]) - 1)

    def test_the_regenerated_run_matches_the_original(self):
        for k in ("status", "class", "capture", "deliveries", "video", "audio", "audio_raw", "next_cause_at_end",
                  "boundaries_gbi", "boundaries_disc", "complete_gbi", "complete_disc", "service", "restore",
                  "t0", "deadline", "refusal", "isr_w1c", "main_w1c", "teardown_w1c", "unmasks", "lean", "verify",
                  "acks" if "acks" in self.original else "unmasks", "errors", "transport_ok", "uncertain"):
            self.assertEqual(self.replayed.get(k), self.original.get(k), k)

    def test_without_the_sidecar_the_blocks_are_reported_missing(self):
        r = subprocess.run([BIN, "--replay", self.fixture], capture_output=True, text=True)
        m = REPLAY_RE.search(r.stdout)
        self.assertIsNotNone(m)
        self.assertGreater(int(m.group(8)), 0)          # blocks_missing
        self.assertNotEqual(r.returncode, 0)            # never passed off as physical bytes

    def test_the_sidecar_parses_and_agrees_with_the_summary(self):
        with open(self.seq, "rb") as f:
            d = avseq.parse(f.read())
        self.assertEqual(d["cycle_count"], int(self.original["deliveries"]))
        self.assertEqual(d["boundaries_gbi"], int(self.original["boundaries_gbi"]))
        self.assertEqual(d["boundaries_disc"], int(self.original["boundaries_disc"]))
        self.assertEqual(d["capture"], self.original["capture"])

    def test_the_generated_files_stay_out_of_the_fixture_directory(self):
        for p in (self.log, self.seq, self.fixture):
            self.assertNotIn(os.path.join("captures", "fixtures"), p)


@unittest.skipUnless(os.path.isfile(BIN) and os.path.isfile(PHYSICAL_AVSVC) and os.path.isfile(PHYSICAL_AVSVC_BLOCKS),
                     "the physical GBP-AV-SERVICE-001 fixture and its sidecar are required")
class PhysicalFirstCycle(unittest.TestCase):
    """The physical AVSVC run is exactly one cycle of the GBP-VIDEO-001 loop."""

    def test_the_unit_test_replays_it(self):
        r = subprocess.run([BIN, PHYSICAL_AVSVC, PHYSICAL_AVSVC_BLOCKS], capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertRegex(r.stdout, r"test_gbp_video: \d+ checks, 0 failures")
        self.assertNotIn("prefix test skipped", r.stderr)

    def test_the_fixture_is_not_modified(self):
        # the raw physical evidence is immutable: the replay only reads it
        before = os.stat(PHYSICAL_AVSVC).st_mtime_ns, os.path.getsize(PHYSICAL_AVSVC)
        subprocess.run([BIN, PHYSICAL_AVSVC, PHYSICAL_AVSVC_BLOCKS], capture_output=True)
        self.assertEqual((os.stat(PHYSICAL_AVSVC).st_mtime_ns, os.path.getsize(PHYSICAL_AVSVC)), before)

    def test_no_physical_video_001_fixture_exists(self):
        names = os.listdir(os.path.join(ROOT, "captures", "fixtures"))
        self.assertFalse([n for n in names if "video" in n.lower()],
                         "GBP-VIDEO-001 has not been physically executed: no fixture may exist")


if __name__ == "__main__":
    unittest.main()
