/*
 * gbp_aresamp — 4096 Hz -> 32 000 Hz, the rate the GameCube's AI wants (Issue #81).
 *
 * EXACT, BY CONSTRUCTION. 32000 / 4096 = 125 / 16. Every input sample produces
 * 7 or 8 outputs, chosen by an INTEGER accumulator stepping 16 per output and
 * 125 per input, so after every 16 inputs exactly 125 outputs have been emitted
 * and the accumulator is back where it started. There is no fractional phase
 * anywhere and nothing to drift, however long it runs.
 *
 * THE FILTER is an interpolating windowed sinc, cutoff at the INPUT Nyquist
 * (2048 Hz), 16 taps, one row per phase in gbp_aresamp_coef.h — generated by
 * tools/gen_aresamp.py and checked against it. Q15, and each row sums to exactly
 * 32768, so the DC gain is exactly 1 at every phase.
 *
 * LATENCY: 8 input samples (1.95 ms). The history starts at zero, i.e. as if the
 * stream were preceded by silence.
 *
 * WHAT IT DOES TO A SHORT PERIOD, said here because it is the case most likely to
 * be misread: at 1024 Hz the 4096 Hz source has four samples per period and can
 * only represent that tone's FUNDAMENTAL (plus a term at exactly the Nyquist,
 * which RUN 33's 1024 Hz window does not have). The upsampled output is therefore
 * a SINE of the fundamental's amplitude — not the square the samples might
 * suggest. Its fundamental comes through at 1.0007 (+0.006 dB). Its PEAK comes
 * out 25 % ABOVE the largest source sample, because four samples per period miss
 * the crest of the sine they sample and a band-limited reconstruction restores
 * it. So a peak comparison reads a GAIN that is not there — from none to 41 %
 * (1/cos 45°), depending only on where the samples happen to fall on the sine
 * (here cos 36.9° = 0.80, hence 25 %): measure the fundamental, never the peak
 * (tests/host/test_audio_runtime.py, The1024HzWindow).
 *
 * Integer only, no allocation, no blocking call.
 */
#ifndef OPENGBP_GBP_ARESAMP_H
#define OPENGBP_GBP_ARESAMP_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GBP_ARESAMP_MAX_OUT 8u          /* ceil(125 / 16): outputs one input can produce */

struct gbp_aresamp {
    int16_t  hist[16];                  /* the last 16 inputs, a ring */
    uint32_t hpos;                      /* where the NEXT input goes */
    uint32_t acc;                       /* next output's phase, in 1/125 of an input sample */
    uint32_t in_count, out_count;
};

void gbp_aresamp_init(struct gbp_aresamp *r);

/* Push one 4096 Hz sample; writes 7 or 8 32 kHz samples to out (room for
 * GBP_ARESAMP_MAX_OUT) and returns how many. */
uint32_t gbp_aresamp_push(struct gbp_aresamp *r, int16_t in, int16_t *out);

#ifdef __cplusplus
}
#endif
#endif
