#!/usr/bin/env python3
"""
tools/gen_aresamp.py -- generate src/audio/gbp_aresamp_coef.h, the 4096 -> 32000 Hz
resampler's coefficient table (Issue #81).

    tools/gen_aresamp.py > src/audio/gbp_aresamp_coef.h

WHY A GENERATOR. The runtime resampler must contain no floating point
(CLAUDE.md §22 and the drain-path rules). The coefficients need a sinc and a
cosine to compute, so they are computed HERE, once, and the C side reads an
integer table. tests/host/test_audio_runtime.py regenerates it and compares
byte for byte with the committed header, so the table cannot drift from this
definition.

THE RATIO IS EXACT. 32000 / 4096 = 125 / 16. Output k sits at input position
k * 16 / 125, so its PHASE -- the fractional part, in units of 1/125 input
sample -- is (16 k) mod 125: one of exactly 125 values, all integers. Every
phase has its own row of taps here, and the C side walks the phase with an
integer accumulator, so the output timebase can never drift from the input's.

THE KERNEL. For phase p and tap m (0..15) the offset is t = 7 - m + p/125 input
samples, and the tap is sinc(t) * hann(t / 8): an interpolating low-pass whose
cutoff is the INPUT Nyquist (2048 Hz), tapered over +-8 input samples. At p = 0
it reduces to a single 1 on tap 7, so an output that lands exactly on an input
sample reproduces that sample.

Q15, and EACH PHASE'S TAPS SUM TO EXACTLY 32768: after rounding, the rounding
residue is folded into the largest tap, so the DC gain is exactly 1 at every
phase and a constant input cannot come out rippled at 7.8 times its rate.

THE TABLE IS int32_t, NOT int16_t, AND THAT IS A BUG FIXED BEFORE IT SHIPPED.
Phase 0 is a single tap of exactly 1.0, which in Q15 is 32768 -- one more than
INT16_MAX. Stored as int16_t it would wrap to -32768 and every output landing on
an input sample would come out with its sign inverted. render() now asserts the
range of the type it emits rather than assuming it.
"""
import math
import sys

IN_RATE, OUT_RATE = 4096, 32000
L, M = 125, 16                    # OUT/IN = L/M exactly
TAPS = 16
HALF = TAPS // 2
Q = 15


def kernel(t):
    s = 1.0 if t == 0 else math.sin(math.pi * t) / (math.pi * t)
    w = 0.5 * (1.0 + math.cos(math.pi * t / HALF)) if abs(t) < HALF else 0.0
    return s * w


def table():
    rows = []
    for p in range(L):
        raw = [kernel(7 - m + p / float(L)) for m in range(TAPS)]
        q = [int(round(h * (1 << Q))) for h in raw]
        resid = (1 << Q) - sum(q)
        big = max(range(TAPS), key=lambda i: abs(q[i]))
        q[big] += resid
        rows.append(q)
    return rows


INT32_MIN, INT32_MAX = -(1 << 31), (1 << 31) - 1


def render():
    assert L * IN_RATE == M * OUT_RATE
    rows = table()
    assert all(INT32_MIN <= v <= INT32_MAX for r in rows for v in r)
    out = ["/* GENERATED by tools/gen_aresamp.py -- do not edit. 4096 -> 32000 Hz, L/M = 125/16,",
           " * Q15, 16 taps per phase, each phase summing to exactly 32768. */",
           "#ifndef OPENGBP_GBP_ARESAMP_COEF_H",
           "#define OPENGBP_GBP_ARESAMP_COEF_H",
           "#define GBP_ARESAMP_L 125u",
           "#define GBP_ARESAMP_M 16u",
           "#define GBP_ARESAMP_TAPS 16u",
           "static const int32_t GBP_ARESAMP_COEF[125][16] = {"]
    for q in rows:
        out.append("    {" + ", ".join("%d" % v for v in q) + "},")
    out += ["};", "#endif", ""]
    return "\n".join(out)


if __name__ == "__main__":
    sys.stdout.write(render())
