#!/usr/bin/env python3
"""
tools/gen_aresamp2.py -- generate src/audio/gbp_aresamp2_coef.h, Round B's native resampler,
65 536 -> 32 000 Hz (GitHub Issue #126; the design settled on #124, GBP-HW-351).

    tools/gen_aresamp2.py > src/audio/gbp_aresamp2_coef.h

THE OBJECT IS THE ONE #124 MEASURED, NOT A REDERIVATION. `tools/v124taps.py`'s `kernel(16, 4.0, per_phase=True,
q15=True, representable=True)` is the exact, already-tested construction GBP-HW-351 settled (16 taps, Kaiser beta
4.0, cutoff at the output's Nyquist 16 000 Hz, the t = +8 tap of phase 0 dropped before normalising, every phase
scaled to sum to exactly 1, then quantised to Q15 with the rounding residue folded into each phase's largest tap).
This tool calls that function and RESHAPES its flat, symmetric output (2001 entries, index n' = centre + n, t =
n / L input samples, centre = 1000) into the [125][16] table `src/audio/gbp_aresamp2.c` walks, using the same
convention `tools/gen_aresamp.py` uses for the 4096 -> 32000 Hz table: tap m of phase p is the kernel's sample at
t = (TAPS/2 - 1) - m + p/L, i.e. flat index `centre + L*(TAPS/2 - 1 - m) + p` (1875 - 125*m + p here). This mapping
is independently re-derived and cross-checked in `tests/host/test_v126_resampler2.py`, which calls
`v124taps.kernel()` itself: a change to EITHER this file or `v124taps.kernel()` that disagrees fails there, never
silently.

THE RATIO IS EXACT: 125 * 65536 == 256 * 32000 (both 8 192 000), which the generator asserts.

Q15, every phase's taps sum to exactly 32768: `tests/host/test_resampler_tables.py` requires this of every
committed two-dimensional resampler table found by declaration, this one included.

Standard library only (imports tools/v124taps.py, which imports tools/v123chain.py and the archive parsers; those
parsers are not exercised by generation, only their module import, so the archive need not be present to run this).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v124taps  # noqa: E402

IN_RATE, OUT_RATE = 65536, 32000
L, M = 125, 256                   # OUT/IN = L/M exactly
TAPS = 16
HALF = TAPS // 2                  # 8
BETA = 4.0
Q = 15

INT32_MIN, INT32_MAX = -(1 << 31), (1 << 31) - 1


def table():
    """[125][16] Q15 ints, tap m of phase p at t = (HALF - 1) - m + p / L, from v124taps.kernel()'s own, already
    settled and tested construction -- not rederived here."""
    h, centre = v124taps.kernel(TAPS, BETA, per_phase=True, q15=True, representable=True)
    qh = [int(round(v * (1 << Q))) for v in h]
    rows = []
    for p in range(L):
        row = [qh[centre + L * (HALF - 1 - m) + p] for m in range(TAPS)]
        assert sum(row) == 1 << Q, (p, sum(row))
        rows.append(row)
    return rows


def render():
    assert L * IN_RATE == M * OUT_RATE
    rows = table()
    assert all(INT32_MIN <= v <= INT32_MAX for r in rows for v in r)
    out = ["/* GENERATED by tools/gen_aresamp2.py -- do not edit. 65536 -> 32000 Hz, L/M = 125/256,",
           " * Q15, 16 taps per phase (Kaiser beta 4.0, GBP-HW-351), each phase summing to exactly 32768.",
           " * Round B (GitHub Issue #126): a NEW path, not a moved default -- gbp_aresamp_coef.h is untouched. */",
           "#ifndef OPENGBP_GBP_ARESAMP2_COEF_H",
           "#define OPENGBP_GBP_ARESAMP2_COEF_H",
           "#define GBP_ARESAMP2_L 125u",
           "#define GBP_ARESAMP2_M 256u",
           "#define GBP_ARESAMP2_TAPS 16u",
           "static const int32_t GBP_ARESAMP2_COEF[125][16] = {"]
    for q in rows:
        out.append("    {" + ", ".join("%d" % v for v in q) + "},")
    out += ["};", "#endif", ""]
    return "\n".join(out)


if __name__ == "__main__":
    sys.stdout.write(render())
