#!/usr/bin/env python3
"""
probelog — parse Open-GBP device logs (OPENGBP-LOG v1, as written by
src/platform/sdlog.c or captured from USB Gecko "OPENGBP-PROBE LOG" lines)
and turn them into machine-readable data, replay fixtures and a
comparison against the Phase 2 expectations.

Usage:
    tools/probelog.py parse   <log>              JSON summary + records
    tools/probelog.py fixture <log> <out.gbpreplay>   replay script for src/gbp/gbp_replay.c
    tools/probelog.py check   <log>              interpret TEST/RAW records (exit 1 on anomalies)

Record grammar (one per line, after the "NNNNNN " sequence prefix):
    KEY key=value key=value ...      values are hex/decimal/strings; data=<64 hex>
The parser keeps every raw block as bytes; interpretation lives in check().
"""
from __future__ import annotations

import json
import re
import sys

REC_RE = re.compile(r"^(?:(\d{6}) )?([A-Z]+)(?: (.*))?$")
KV_RE = re.compile(r"(\w+)=(\S+)")


def parse_lines(lines):
    """Yields dicts: {seq, kind, fields:{...}} for record lines; header
    key=value lines go to a dict returned separately."""
    header = {}
    records = []
    for raw in lines:
        s = raw.rstrip("\r\n")
        if s.startswith("OPENGBP-PROBE LOG "):
            s = s[len("OPENGBP-PROBE LOG "):]
        if not s or s.startswith("#"):
            continue
        m = REC_RE.match(s)
        if m and m.group(2) and (m.group(1) is not None or m.group(2).isupper()):
            seq, kind, rest = m.groups()
            if seq is None and "=" in kind:
                pass
            else:
                fields = dict(KV_RE.findall(rest or ""))
                toks = (rest or "").split()
                tag = toks[0] if toks and "=" not in toks[0] else None
                if "data" in fields and fields["data"] != "-":
                    try:
                        fields["data_bytes"] = bytes.fromhex(fields["data"])
                    except ValueError:
                        fields["data_bytes"] = None
                records.append({"seq": int(seq) if seq else None, "kind": kind, "tag": tag, "fields": fields})
                continue
        if "=" in s and " " not in s.split("=", 1)[0]:
            k, v = s.split("=", 1)
            header[k] = v
    return header, records


def parse_file(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return parse_lines(f.readlines())


def to_json(header, records):
    out = {"header": header, "records": []}
    for r in records:
        f = dict(r["fields"])
        if "data_bytes" in f:
            f["data_bytes"] = f["data_bytes"].hex() if f["data_bytes"] else None
        out["records"].append({"seq": r["seq"], "kind": r["kind"], "tag": r.get("tag"), "fields": f})
    return out


def fixture(records):
    """Replay script: reproduces the transport calls the probe made, in
    order, so gbp_replay + gbp_probe on the host reach the same result."""
    lines = ["# generated by tools/probelog.py from a device log"]
    for r in records:
        k, f, tag = r["kind"], r["fields"], r.get("tag")
        if k == "ARINFO" and "value" in f:
            if tag in ("write", "restore"):
                lines.append("A w %s" % f["value"])
            elif f.get("rc", "ok") == "ok":
                lines.append("A r %s" % f["value"])
        elif k == "RAW":
            data = f.get("data", "-") if f.get("rc") == "ok" else ""
            lines.append(("R %s %s %s" % (f["addr"], f["rc"], data)).rstrip())
        elif k == "TESTW":
            lines.append("W %s %s" % (f.get("addr") or _hs_addr(records, r), f["rc"]))
        elif k == "TESTR":
            data = f.get("data", "-") if f.get("rc") == "ok" else ""
            lines.append(("R %s %s %s" % (f.get("addr") or _hs_addr(records, r), f["rc"], data)).rstrip())
        elif k == "CTLW":
            lines.append("W %s %s" % (f["addr"], f["rc"]))
        elif k == "PI" and "intsr" in f:
            lines.append("P r %s %s" % (f["intsr"], f["intmr"]))
        elif k == "INTMR" and tag in ("mask", "restore") and f.get("rc") == "ok":
            lines.append("P w %s" % (f.get("readback") or f.get("wanted") or f.get("value")))
    return "\n".join(lines) + "\n"


def _hs_addr(records, rec):
    """Handshake records carry idx but not addr; derive base from the
    preceding MODE begin record."""
    base = None
    for r in records:
        if r is rec:
            break
        if r["kind"] == "MODE" and r["fields"].get("base"):
            base = int(r["fields"]["base"], 16)
    idx = int(rec["fields"].get("idx", "0"), 16)
    return "%08x" % ((base or 0) + (idx << 20))


def check(header, records):
    """Interpretation pass. Returns (findings:list[str], anomalies:int)."""
    findings = []
    anomalies = 0
    modes = {}
    for r in records:
        f = r["fields"]
        if r["kind"] == "TESTR" and f.get("rc") == "ok" and f.get("data_bytes"):
            d = f["data_bytes"]
            exp = int(f["expect"], 16)
            uniq = sorted(set(d))
            m = f.get("mode", "?")
            modes.setdefault(m, {"tests": 0, "all": 0, "b1f": 0, "layouts": set()})
            modes[m]["tests"] += 1
            if all(b == exp for b in d):
                modes[m]["all"] += 1
                modes[m]["layouts"].add("uniform")
            elif d[31] == exp:
                modes[m]["b1f"] += 1
                modes[m]["layouts"].add("byte1F-only:" + d.hex())
            else:
                modes[m]["layouts"].add("nomatch:" + d.hex())
            if len(uniq) > 2:
                findings.append("seq %s: TESTR mode=%s pattern=%s has %d distinct byte values" % (r["seq"], m, f.get("pattern"), len(uniq)))
        if r["kind"] == "RAW" and f.get("rc") != "ok":
            anomalies += 1
            findings.append("seq %s: RAW idx=%s rc=%s" % (r["seq"], f.get("idx"), f.get("rc")))
        if r["kind"] == "PROBE" and "restored=0" in " ".join("%s=%s" % kv for kv in f.items()):
            anomalies += 1
            findings.append("AR_INFO NOT restored")
    for m, s in sorted(modes.items()):
        findings.append("mode %s: %d handshakes, %d uniform inverse, %d byte1F-only; layouts=%s"
                        % (m, s["tests"], s["all"], s["b1f"], sorted(s["layouts"])))
    return findings, anomalies


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) < 2:
        print(__doc__)
        return 2
    cmd, path = argv[0], argv[1]
    header, records = parse_file(path)
    if cmd == "parse":
        print(json.dumps(to_json(header, records), indent=1))
        return 0
    if cmd == "fixture":
        if len(argv) < 3:
            print("fixture needs an output path", file=sys.stderr)
            return 2
        with open(argv[2], "w", encoding="utf-8") as f:
            f.write(fixture(records))
        print("wrote %s (%d records)" % (argv[2], len(records)))
        return 0
    if cmd == "check":
        findings, anomalies = check(header, records)
        for l in findings:
            print(l)
        print("anomalies=%d" % anomalies)
        return 1 if anomalies else 0
    print("unknown command", cmd, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
