#!/usr/bin/env python3
"""
tools/u045arms.py — RUN 40 by arm (GitHub Issue #108): is the half arm's residue still `produce`, and did
the VIDEO loss follow the arms too? DESCRIPTIVE: §V24 pre-registered no gate for either question, and this
file decides nothing.

    tools/u045arms.py <report JSON from tools/v24report.py> [--json <out>]

EVERY RULE IT USES IS A FROZEN ONE, not a new one:
  the arms      a cycle takes the arm of the one chunk whose production steps fall in it -- §V24.7 (r5), the
                assignment regenerated by tools/v24accept.py's arms(), the tags read as tools/v24accept.py reads them
  the losses    tools/v23accept.py's audio_losses(), each mapped to the cycle of the callback before its tick
  P by arm      tools/v23accept.py's question_P(), called on each arm's losses -- the same attribution, split
  VIDEO gaps    tools/v23accept.py's video_gaps(), inside the AI span, each mapped to a cycle by its frozen time
                (the completion after the gap)

WHAT THE VIDEO MAPPING CAN AND CANNOT DO. A VIDEO gap's time is the completion that ends it; where the frame's
largest intra-frame gap is a close call, the true gap may sit elsewhere in the frame. The report therefore gives:
  by gap time            every gap, mapped by its frozen time
  clear gaps only        the gaps whose frame's largest gap is at least 1.2 x the second largest
  whole frames           the incomplete frames whose first and last block fall inside ONE analysed cycle
A misplaced gap moves to a neighbouring cycle, which the pair-balanced assignment makes the other arm about half
the time: misplacement dilutes an arm difference toward none, it cannot make one.

Beside each count: the one-sided exact binomial tail of the half arm's share under "the arm does not matter"
(p0 = the half arm's share of analysed cycles). CONTEXT ONLY: post hoc, no gate, several cuts.

Standard library only; reads a report, writes the JSON it is asked to.
"""
import bisect
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import v23accept  # noqa: E402
import v24accept  # noqa: E402

TB_HZ = 40500000
CLEAR = 1.2


def binom_tail_le(k, n, p):
    """P(X <= k) for X ~ Binomial(n, p)."""
    return sum(math.comb(n, i) * p ** i * (1 - p) ** (n - i) for i in range(k + 1))


def arms_of_cycles(report):
    ent = sorted(c[0] for c in report["callbacks"])
    ncyc = max(0, len(ent) - 1)
    seq, prod = -1, []
    for s, tag in zip(report["steps"], report["step_tag"]):
        if s[2] != "produce":
            continue
        if tag & 2:
            seq += 1
        prod.append((s, seq))
    want = v24accept.arms(seq + 1)
    chunks = [set() for _ in range(ncyc)]
    for s, q in prod:
        c = bisect.bisect_right(ent, s[0]) - 1
        if 0 <= c < ncyc:
            chunks[c].add(q)
    return ent, dict((c, want[next(iter(chunks[c]))]) for c in range(ncyc) if len(chunks[c]) == 1)


def by_arm(report):
    ent, arm_of = arms_of_cycles(report)
    n_half = sum(1 for a in arm_of.values() if a == 1)
    n_full = sum(1 for a in arm_of.values() if a == 0)
    p0 = n_half / float(n_half + n_full)

    def arm_at(t):
        return arm_of.get(bisect.bisect_right(ent, t) - 1)

    def share(h, f):
        n = h + f
        return {"half": h, "full": f, "half_share": (h / float(n)) if n else None,
                "binomial_tail_le": binom_tail_le(h, n, p0) if n else None}

    a = report["audio"]
    losses = v23accept.audio_losses(a["decoded"], a["ticks"])
    split = {1: [], 0: [], None: []}
    for x in losses:
        split[arm_at(x["t"])].append(x)
    P = {}
    for arm, name in ((1, "half"), (0, "full")):
        p = v23accept.question_P(split[arm], report.get("steps", []), report.get("callbacks", []), TB_HZ)
        P[name] = {"losses": p["losses"], "counts": p["counts"], "decision": p["decision"]}
    neither = share(P["half"]["counts"]["neither"], P["full"]["counts"]["neither"])
    produce = share(P["half"]["counts"]["produce"], P["full"]["counts"]["produce"])

    vt, vs = report["video"]["ticks"], report["video"]["start"]
    gaps, _an = v23accept.video_gaps(vt, vs)
    ai0, ai1 = report["ai_span"]
    inside = [g for g in gaps if ai0 <= g["t"] <= ai1]
    by_t = {1: 0, 0: 0, None: 0}
    clear = {1: 0, 0: 0, None: 0}
    for g in inside:
        by_t[arm_at(g["t"])] += 1
        if g["confidence"] is not None and g["confidence"] >= CLEAR:
            clear[arm_at(g["t"])] += 1
    starts = [i for i, s in enumerate(vs) if s]
    start_t = [vt[i] for i in starts]
    frames = {}
    for g in inside:
        frames.setdefault(bisect.bisect_right(start_t, g["t"]) - 1, []).append(g)
    whole = {1: 0, 0: 0}
    straddling = 0
    for i in frames:
        first = vt[starts[i]]
        last = vt[starts[i + 1] - 1] if i + 1 < len(starts) else vt[-1]
        ca, cb = bisect.bisect_right(ent, first) - 1, bisect.bisect_right(ent, last) - 1
        if ca == cb and ca in arm_of:
            whole[arm_of[ca]] += 1
        else:
            straddling += 1
    phase = [0] * 10
    for g in inside:
        c = bisect.bisect_right(ent, g["t"]) - 1
        if 0 <= c < len(ent) - 1:
            phase[min(9, int((g["t"] - ent[c]) * 10.0 / (ent[c + 1] - ent[c])))] += 1
    return {"cycles": {"half": n_half, "full": n_full, "half_share": p0},
            "P_by_arm": P, "losses_outside_analysed_cycles": len(split[None]),
            "neither_by_arm": neither, "produce_by_arm": produce,
            "video": {"gaps_inside_ai_span": len(inside),
                      "by_gap_time": dict(share(by_t[1], by_t[0]), unassigned=by_t[None]),
                      "clear_gaps_only": dict(share(clear[1], clear[0]), unassigned=clear[None]),
                      "incomplete_frames": len(frames),
                      "whole_frames": {"half": whole[1], "full": whole[0], "straddling_or_unassigned": straddling},
                      "gap_phase_deciles": phase},
            "status": "DESCRIPTIVE: §V24 pre-registered no gate for any of this; the binomial tails are context only"}


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    with open(argv[1], encoding="utf-8") as f:
        out = by_arm(json.load(f))
    text = json.dumps(out, indent=2, sort_keys=True)
    if "--json" in argv:
        with open(argv[argv.index("--json") + 1], "w", encoding="utf-8") as f:
            f.write(text + "\n")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
